### ISSUE TITLE
Hearing Impaired to Uppercase crashes

### ISSUE THREAD

**Issue by niksedk** [SubtitleEdit/plugins#249]
![image](https://github.com/user-attachments/assets/5d152625-a3b4-4aa6-be5c-9409787c71b7)

Exception has been thrown by the target of an invocation.
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Nikse.SubtitleEdit.Forms.Main.CallPlugin(Object sender, Boolean allowChangeFormat, Boolean translate) in C:\git\subtitleedit\src\ui\Forms\Main.cs:line 27257

Index was outside the bounds of the array.
   at Nikse.SubtitleEdit.PluginLogic.Converters.MoodCasingConverter.HasValidMood(String text)
   at Nikse.SubtitleEdit.PluginLogic.Converters.MoodCasingConverter.MoodsToUppercase(String text)
   at Nikse.SubtitleEdit.PluginLogic.Converters.MoodCasingConverter.Convert(IList`1 paragraphs, ConverterContext converterContext)
   at Nikse.SubtitleEdit.PluginLogic.PluginForm.GeneratePreview()
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at Nikse.SubtitleEdit.PluginLogic.PluginForm..ctor(Subtitle subtitle, String name, String description)
   at Nikse.SubtitleEdit.PluginLogic.HI2UC.DoAction(Form parentForm, String srtText, Double frame, String uiLineBreak, String file, String videoFile, String rawText)

[sub.zip](https://github.com/user-attachments/files/17791640/sub.zip)

@ivandrofly : can you take a look?

**Comment by ivandrofly** [comment]
Checking...

**Comment by ivandrofly** [comment]
Pushing fix in few... bug in https://github.com/SubtitleEdit/plugins/blob/d20c5e74bdd8d4f0199007ad823d113eed39c639/HI2UC/Converters/MoodCasingConverter.cs#L156

**Comment by niksedk** [comment]
Thx :)
